### ISSUE TITLE
Problem with WaitForEvents

### ISSUE THREAD

**Issue by sherrinm** [JuliaGPU/CUBLAS.jl#11]
I think this is an issue in CLBLAS although the error is being raised in the OpenCL api.jl

I was looking at the clblasSaxpy.jl example for a talk I'm giving on OpenCL and got:

julia> cl.api.clWaitForEvents(cl.cl_uint(1), ptrEvent)
WARNING: ccall Ptr argument types must now match exactly. or be Ptr(Void).
 in clWaitForEvents at C:\Users\Malcolm.julia\v0.3\OpenCL\src\api.jl:22

The code still seems to execute, not looked at the other examples as yet.
I'm running on a Lenovo i7 with GeForce 830M chip on Windows

**Comment by vchuravy** [comment]
@sherrinm This is the CUBLAS issues tracker, you might have confused that the the CLBLAS repository https://github.com/JuliaGPU/CLBLAS.jl
